In [7]:
import numpy as np
np.random.rand(4,4)
randMat=np.mat(np.random.rand(4,4))
#矩阵取.I操作可取逆
print(randMat*randMat.I)

[[  1.00000000e+00  -1.38777878e-17   2.77555756e-17  -2.42861287e-17]
 [ -1.38777878e-17   1.00000000e+00   0.00000000e+00  -1.52655666e-16]
 [  0.00000000e+00  -1.11022302e-16   1.00000000e+00  -1.11022302e-16]
 [  1.11022302e-16   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
